name: Run Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Adjust the Node.js version to your requirement

    - name: Install dependencies
      run: |
        npm install
        npm install vite-plugin-pwa --save-dev  # Install vite-plugin-pwa
      working-directory: ./geo-have  # Adjust the path to the correct directory

    - name: Run tests
      run: npm run test:unit
      working-directory: ./geo-have  # Adjust the path to the correct directory
