name: Run Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: geo-have  # Specify the correct path to your repository folder

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install
      working-directory: geo-have  # Set the working directory to the correct folder

    - name: Run tests
      run: npm test
      working-directory: geo-have  # Set the working directory to the correct folder
